trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    mkdir build
    cd build
    cmake ..
    make
    cpack
  displayName: 'Build xcshim'

- script: |
    mkdir dist
    cd build
    DESTDIR=../dist make install
  displayName: 'Package xcshim'

- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)/pkg

    # Create a source tarball
    git archive --output $(Build.ArtifactStagingDirectory)/pkg/xcshim.0.1.tar.gz HEAD

    # Copy over the Debian package
    cp build/*.deb $(Build.ArtifactStagingDirectory)/pkg/

    # Copy over the RedHat package
    cp build/*.rpm $(Build.ArtifactStagingDirectory)/pkg/

    # Create a binary tarball
    cd dist
    tar cvzf $(Build.ArtifactStagingDirectory)/pkg/xcdist.0.1.dist.tar.gz .
  displayName: 'Prepare artifacts'

- publish: $(Build.ArtifactStagingDirectory)/pkg
  artifact: pkg
